import React from 'react';
import { X, User, Users, Shield, Award, Calendar } from 'lucide-react';
import Badge from '../../components/Common/Badge';
import './Groups.css'; // We'll rely on the existing CSS file which we'll update

const GroupsModal = ({ isOpen, onClose, group }) => {
    if (!isOpen || !group) return null;

    return (
        <div className="groups-modal-overlay" onClick={onClose}>
            <div
                className="groups-modal-container glass animate-scale-in"
                onClick={e => e.stopPropagation()}
            >
                {/* Header */}
                <div className="groups-modal-header">
                    <div className="header-content">
                        <div className="icon-wrapper">
                            <Users size={24} color="white" />
                        </div>
                        <div>
                            <h2>{group.name}</h2>
                            <span className="subtitle">{group.members.length} Active Members</span>
                        </div>
                    </div>
                    <button className="close-button" onClick={onClose}>
                        <X size={20} />
                    </button>
                </div>

                {/* Content */}
                <div className="groups-modal-body custom-scrollbar">

                    {/* Stats Row */}
                    <div className="stats-row">
                        <div className="stat-card glass">
                            <div className="stat-icon"><Shield size={16} color="var(--accent-success)" /></div>
                            <div className="stat-info">
                                <span className="label">Health Score</span>
                                <span className="value">98%</span>
                            </div>
                        </div>
                        <div className="stat-card glass">
                            <div className="stat-icon"><Award size={16} color="var(--accent-warning)" /></div>
                            <div className="stat-info">
                                <span className="label">Top Performance</span>
                                <span className="value">Rank A</span>
                            </div>
                        </div>
                        <div className="stat-card glass">
                            <div className="stat-icon"><Calendar size={16} color="var(--accent-primary)" /></div>
                            <div className="stat-info">
                                <span className="label">Last Activity</span>
                                <span className="value">Today</span>
                            </div>
                        </div>
                    </div>

                    <div className="section-title">
                        <h3>Member Composition</h3>
                        <div className="line"></div>
                    </div>

                    <div className="members-grid">
                        {group.members.map((member, idx) => (
                            <div key={idx} className="member-card glass hover-lift">
                                <div className="member-avatar-placeholder">
                                    <User size={18} />
                                </div>
                                <div className="member-details">
                                    <span className="uid">{member}</span>
                                    <span className="role">Student</span>
                                </div>
                                <Badge type="success" className="status-badge">Active</Badge>
                            </div>
                        ))}
                    </div>
                </div>

                {/* Footer */}
                <div className="groups-modal-footer">
                    <div className="footer-info">
                        Generated by AI Clustering
                    </div>
                    <button className="action-button" onClick={onClose}>
                        Close Overview
                    </button>
                </div>
            </div>
        </div>
    );
};

export default GroupsModal;
